const Engine = Matter.Engine;
const World = Matter.World;
const Body = Matter.Body;
const Bodies = Matter.Bodies;
const Constraint = Matter.Constraint;

var engine , world;
var Man , THUNder;
var ManWalk;
var a1 , a2 , a3 , a4;
var StrickMoment;
var DISWIDTH , DISHEIGHT ;
var drop1 , drop2 , drop3 , drop4 , drop5 , drop6 , drop7 , drop8 , drop9 , drop10 , drop11 , drop12 , drop13 , drop14 , drop15 , drop16 , drop17 , drop18 , drop19 , drop20;
var drop21 , drop22 , drop23 , drop24 , drop25 , drop26 , drop27 , drop28 , drop29 , drop30 , drop31 , drop32 , drop33 , drop34 , drop35 , drop36 , drop37 , drop38 , drop39 , drop40;
var drop41 , drop42 , drop43 , drop44 , drop45 , drop46 , drop47 , drop48 , drop49 , drop50 , drop51 , drop52 , drop53 , drop54 , drop55 , drop56 , drop57 , drop58 , drop59 , drop60;
var drop61 , drop62 , drop63 , drop64 , drop65 , drop66 , drop67 , drop68 , drop69 , drop70 , drop71 , drop72 , drop73 , drop74 , drop75 , drop76 , drop77 , drop78 , drop79 , drop80;
var drop81 , drop82 , drop83 , drop84 , drop85 , drop86 , drop87 , drop88 , drop89 , drop90 , drop91 , drop92 , drop93 , drop94 , drop95 , drop96 , drop97 , drop98 , drop99 , drop100;

function preload()
{
    ManWalk = loadImage( 'walking_1.png' );
    a1 = loadImage('images/thunderbolt/1.png');
    a2 = loadImage('images/thunderbolt/2.png');
    a3 = loadImage('images/thunderbolt/3.png');
    a4 = loadImage('images/thunderbolt/4.png');
}

function setup()
{
    engine = Engine.create();
    world = engine.world;
        
    createCanvas( displayWidth , displayHeight );
    Man = new UMBRELLA(displayWidth/2-150 , displayHeight-400 , 350 , 400 , true , 0 , 0 );
    THUNder = createSprite( displayWidth/2 , 50 , 100 , 100 );
    drop1 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop2 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop3 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop4 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop5 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop6 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop7 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop8 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop9 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop10 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop11 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop12 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop13 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop14 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop15 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop16 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop17 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop18 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop19 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop20 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop21 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop22 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop23 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop24 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop25 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop26 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop27 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop28 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop29 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop30 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop31 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop32 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop33 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop34 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop35 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop36 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop37 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop38 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop39 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop40 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop41 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop42 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop43 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop44 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop45 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop46 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop47 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop48 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop49 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop50 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop51 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop52 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop53 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop54 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop55 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop56 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop57 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop58 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop59 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop60 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop61 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop62 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop63 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop64 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop65 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop66 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop67 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop68 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop69 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop70 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop71 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop72 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop73 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop74 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop75 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop76 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop77 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop78 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop79 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop80 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop81 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop82 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop83 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop84 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop85 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop86 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop87 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop88 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop89 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop90 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop91 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop92 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop93 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop94 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop95 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop96 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop97 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop98 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop99 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    drop100 = new DROP( random( 1 , displayWidth ) , 1 , 5 );
    
    THUNder.visible = false;
    DISWIDTH = displayWidth;
    DISHEIGHT = displayHeight;
}

function draw()
{
    background( "black" );
    drawSprites();
    Man.display("white");
    THUNder.visible = false;
    if( frameCount%72===0 )
    {
        StrickMoment = frameCount;
        thunder();
        THUNder.visible = true;
    }
    if( frameCount - StrickMoment < 10 )
    {
        THUNder.visible = true;
    }
    drop1.display( "white" );
    drop2.display( "white" );
    drop3.display( "white" );
    drop4.display( "white" );
    drop5.display( "white" );
    drop6.display( "white" );
    drop7.display( "white" );
    drop8.display( "white" );
    drop9.display( "white" );
    drop10.display( "white" );
    drop11.display( "white" );
    drop12.display( "white" );
    drop13.display( "white" );
    drop14.display( "white" );
    drop15.display( "white" );
    drop16.display( "white" );
    drop17.display( "white" );
    drop18.display( "white" );
    drop19.display( "white" );
    drop20.display( "white" );
    drop21.display( "white" );
    drop22.display( "white" );
    drop23.display( "white" );
    drop24.display( "white" );
    drop25.display( "white" );
    drop26.display( "white" );
    drop27.display( "white" );
    drop28.display( "white" );
    drop29.display( "white" );
    drop30.display( "white" );
    drop31.display( "white" );
    drop32.display( "white" );
    drop33.display( "white" );
    drop34.display( "white" );
    drop35.display( "white" );
    drop36.display( "white" );
    drop37.display( "white" );
    drop38.display( "white" );
    drop39.display( "white" );
    drop40.display( "white" );
    drop41.display( "white" );
    drop42.display( "white" );
    drop43.display( "white" );
    drop44.display( "white" );
    drop45.display( "white" );
    drop46.display( "white" );
    drop47.display( "white" );
    drop48.display( "white" );
    drop49.display( "white" );
    drop50.display( "white" );
    drop51.display( "white" );
    drop52.display( "white" );
    drop53.display( "white" );
    drop54.display( "white" );
    drop55.display( "white" );
    drop56.display( "white" );
    drop57.display( "white" );
    drop58.display( "white" );
    drop59.display( "white" );
    drop60.display( "white" );
    drop61.display( "white" );
    drop62.display( "white" );
    drop63.display( "white" );
    drop64.display( "white" );
    drop65.display( "white" );
    drop66.display( "white" );
    drop67.display( "white" );
    drop68.display( "white" );
    drop69.display( "white" );
    drop70.display( "white" );
    drop71.display( "white" );
    drop72.display( "white" );
    drop73.display( "white" );
    drop74.display( "white" );
    drop75.display( "white" );
    drop76.display( "white" );
    drop77.display( "white" );
    drop78.display( "white" );
    drop79.display( "white" );
    drop80.display( "white" );
    drop81.display( "white" );
    drop82.display( "white" );
    drop83.display( "white" );
    drop84.display( "white" );
    drop85.display( "white" );
    drop86.display( "white" );
    drop87.display( "white" );
    drop88.display( "white" );
    drop89.display( "white" );
    drop90.display( "white" );
    drop91.display( "white" );
    drop92.display( "white" );
    drop93.display( "white" );
    drop94.display( "white" );
    drop95.display( "white" );
    drop96.display( "white" );
    drop97.display( "white" );
    drop98.display( "white" );
    drop99.display( "white" );
    drop100.display( "white" );
}   


